// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SpilSalesOrder.Infrastructure.Data;

#nullable disable

namespace SpilSalesOrder.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251120223103_SeedItemData")]
    partial class SeedItemData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SpilSalesOrder.Domain.Entities.Customer", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("AddressLine1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AddressLine2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Customer");

                    b.HasData(
                        new
                        {
                            id = 1,
                            AddressLine1 = "10 Galle Road",
                            AddressLine2 = "Colombo 03",
                            City = "Colombo",
                            CustomerName = "Ariya Perera",
                            PostalCode = "00300"
                        },
                        new
                        {
                            id = 2,
                            AddressLine1 = "25 Kandy Road",
                            AddressLine2 = "Peradeniya",
                            City = "Kandy",
                            CustomerName = "Saman Kumara",
                            PostalCode = "20400"
                        },
                        new
                        {
                            id = 3,
                            AddressLine1 = "5 Main Street",
                            AddressLine2 = "Mount Lavinia",
                            City = "Mount Lavinia",
                            CustomerName = "Nimali Fernando",
                            PostalCode = "10370"
                        },
                        new
                        {
                            id = 4,
                            AddressLine1 = "Borella Cross Road",
                            AddressLine2 = "Borella",
                            City = "Colombo",
                            CustomerName = "Chamara Silva",
                            PostalCode = "00800"
                        },
                        new
                        {
                            id = 5,
                            AddressLine1 = "15 Station Road",
                            AddressLine2 = "Dehiwala",
                            City = "Dehiwala",
                            CustomerName = "Priya Rajapakse",
                            PostalCode = "10350"
                        });
                });

            modelBuilder.Entity("SpilSalesOrder.Domain.Entities.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ItemCode")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TaxRate")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Item");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Laptop",
                            ItemCode = 1001,
                            Price = 1200.00m,
                            TaxRate = 0.15m
                        },
                        new
                        {
                            Id = 2,
                            Description = "Mouse",
                            ItemCode = 1002,
                            Price = 25.00m,
                            TaxRate = 0.15m
                        },
                        new
                        {
                            Id = 3,
                            Description = "Keyboard",
                            ItemCode = 1003,
                            Price = 75.00m,
                            TaxRate = 0.15m
                        },
                        new
                        {
                            Id = 4,
                            Description = "Monitor",
                            ItemCode = 1004,
                            Price = 300.00m,
                            TaxRate = 0.15m
                        },
                        new
                        {
                            Id = 5,
                            Description = "Webcam",
                            ItemCode = 1005,
                            Price = 50.00m,
                            TaxRate = 0.15m
                        });
                });

            modelBuilder.Entity("SpilSalesOrder.Domain.Entities.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("ExclAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("InclAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ItemCode")
                        .HasColumnType("int");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("SalesOrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("TaxAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TaxRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("SalesOrderId");

                    b.ToTable("SalesOrderItem");
                });

            modelBuilder.Entity("SpilSalesOrder.Domain.Entities.SalesOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AddressLine1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AddressLine2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("InvoiceDate")
                        .HasColumnType("date");

                    b.Property<string>("InvoiceNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReferenceNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalExel")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalIncl")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalTax")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("SalesOrder");
                });

            modelBuilder.Entity("SpilSalesOrder.Domain.Entities.OrderItem", b =>
                {
                    b.HasOne("SpilSalesOrder.Domain.Entities.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SpilSalesOrder.Domain.Entities.SalesOrder", "SalesOrder")
                        .WithMany("OrderItemsList")
                        .HasForeignKey("SalesOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("SalesOrder");
                });

            modelBuilder.Entity("SpilSalesOrder.Domain.Entities.SalesOrder", b =>
                {
                    b.HasOne("SpilSalesOrder.Domain.Entities.Customer", "Customer")
                        .WithMany("SalesOrder")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("SpilSalesOrder.Domain.Entities.Customer", b =>
                {
                    b.Navigation("SalesOrder");
                });

            modelBuilder.Entity("SpilSalesOrder.Domain.Entities.SalesOrder", b =>
                {
                    b.Navigation("OrderItemsList");
                });
#pragma warning restore 612, 618
        }
    }
}
